services:
  postgres:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hxcuber
      POSTGRES_PASSWORD: hxcuber
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: >
      sh -c "psql -U hxcuber -c 'create table test' -c '\l'" 

  api:
    image: hollywood-api
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
