// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Actor is an object representing the database table.
type Actor struct {
	ActorID   int64     `boil:"actor_id" json:"actor_id" toml:"actor_id" yaml:"actor_id"`
	FirstName string    `boil:"first_name" json:"first_name" toml:"first_name" yaml:"first_name"`
	LastName  string    `boil:"last_name" json:"last_name" toml:"last_name" yaml:"last_name"`
	Gender    string    `boil:"gender" json:"gender" toml:"gender" yaml:"gender"`
	Dob       time.Time `boil:"dob" json:"dob" toml:"dob" yaml:"dob"`
	Email     string    `boil:"email" json:"email" toml:"email" yaml:"email"`

	R *actorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L actorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ActorColumns = struct {
	ActorID   string
	FirstName string
	LastName  string
	Gender    string
	Dob       string
	Email     string
}{
	ActorID:   "actor_id",
	FirstName: "first_name",
	LastName:  "last_name",
	Gender:    "gender",
	Dob:       "dob",
	Email:     "email",
}

var ActorTableColumns = struct {
	ActorID   string
	FirstName string
	LastName  string
	Gender    string
	Dob       string
	Email     string
}{
	ActorID:   "actors.actor_id",
	FirstName: "actors.first_name",
	LastName:  "actors.last_name",
	Gender:    "actors.gender",
	Dob:       "actors.dob",
	Email:     "actors.email",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var ActorWhere = struct {
	ActorID   whereHelperint64
	FirstName whereHelperstring
	LastName  whereHelperstring
	Gender    whereHelperstring
	Dob       whereHelpertime_Time
	Email     whereHelperstring
}{
	ActorID:   whereHelperint64{field: "\"actors\".\"actor_id\""},
	FirstName: whereHelperstring{field: "\"actors\".\"first_name\""},
	LastName:  whereHelperstring{field: "\"actors\".\"last_name\""},
	Gender:    whereHelperstring{field: "\"actors\".\"gender\""},
	Dob:       whereHelpertime_Time{field: "\"actors\".\"dob\""},
	Email:     whereHelperstring{field: "\"actors\".\"email\""},
}

// ActorRels is where relationship names are stored.
var ActorRels = struct {
	MainActorMovies string
}{
	MainActorMovies: "MainActorMovies",
}

// actorR is where relationships are stored.
type actorR struct {
	MainActorMovies MovieSlice `boil:"MainActorMovies" json:"MainActorMovies" toml:"MainActorMovies" yaml:"MainActorMovies"`
}

// NewStruct creates a new relationship struct
func (*actorR) NewStruct() *actorR {
	return &actorR{}
}

func (r *actorR) GetMainActorMovies() MovieSlice {
	if r == nil {
		return nil
	}
	return r.MainActorMovies
}

// actorL is where Load methods for each relationship are stored.
type actorL struct{}

var (
	actorAllColumns            = []string{"actor_id", "first_name", "last_name", "gender", "dob", "email"}
	actorColumnsWithoutDefault = []string{"first_name", "last_name", "gender", "dob", "email"}
	actorColumnsWithDefault    = []string{"actor_id"}
	actorPrimaryKeyColumns     = []string{"actor_id"}
	actorGeneratedColumns      = []string{}
)

type (
	// ActorSlice is an alias for a slice of pointers to Actor.
	// This should almost always be used instead of []Actor.
	ActorSlice []*Actor
	// ActorHook is the signature for custom Actor hook methods
	ActorHook func(context.Context, boil.ContextExecutor, *Actor) error

	actorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	actorType                 = reflect.TypeOf(&Actor{})
	actorMapping              = queries.MakeStructMapping(actorType)
	actorPrimaryKeyMapping, _ = queries.BindMapping(actorType, actorMapping, actorPrimaryKeyColumns)
	actorInsertCacheMut       sync.RWMutex
	actorInsertCache          = make(map[string]insertCache)
	actorUpdateCacheMut       sync.RWMutex
	actorUpdateCache          = make(map[string]updateCache)
	actorUpsertCacheMut       sync.RWMutex
	actorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var actorAfterSelectHooks []ActorHook

var actorBeforeInsertHooks []ActorHook
var actorAfterInsertHooks []ActorHook

var actorBeforeUpdateHooks []ActorHook
var actorAfterUpdateHooks []ActorHook

var actorBeforeDeleteHooks []ActorHook
var actorAfterDeleteHooks []ActorHook

var actorBeforeUpsertHooks []ActorHook
var actorAfterUpsertHooks []ActorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Actor) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Actor) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Actor) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Actor) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Actor) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Actor) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Actor) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Actor) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Actor) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddActorHook registers your hook function for all future operations.
func AddActorHook(hookPoint boil.HookPoint, actorHook ActorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		actorAfterSelectHooks = append(actorAfterSelectHooks, actorHook)
	case boil.BeforeInsertHook:
		actorBeforeInsertHooks = append(actorBeforeInsertHooks, actorHook)
	case boil.AfterInsertHook:
		actorAfterInsertHooks = append(actorAfterInsertHooks, actorHook)
	case boil.BeforeUpdateHook:
		actorBeforeUpdateHooks = append(actorBeforeUpdateHooks, actorHook)
	case boil.AfterUpdateHook:
		actorAfterUpdateHooks = append(actorAfterUpdateHooks, actorHook)
	case boil.BeforeDeleteHook:
		actorBeforeDeleteHooks = append(actorBeforeDeleteHooks, actorHook)
	case boil.AfterDeleteHook:
		actorAfterDeleteHooks = append(actorAfterDeleteHooks, actorHook)
	case boil.BeforeUpsertHook:
		actorBeforeUpsertHooks = append(actorBeforeUpsertHooks, actorHook)
	case boil.AfterUpsertHook:
		actorAfterUpsertHooks = append(actorAfterUpsertHooks, actorHook)
	}
}

// One returns a single actor record from the query.
func (q actorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Actor, error) {
	o := &Actor{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for actors")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Actor records from the query.
func (q actorQuery) All(ctx context.Context, exec boil.ContextExecutor) (ActorSlice, error) {
	var o []*Actor

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Actor slice")
	}

	if len(actorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Actor records in the query.
func (q actorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count actors rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q actorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if actors exists")
	}

	return count > 0, nil
}

// MainActorMovies retrieves all the movie's Movies with an executor via main_actor_id column.
func (o *Actor) MainActorMovies(mods ...qm.QueryMod) movieQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"movies\".\"main_actor_id\"=?", o.ActorID),
	)

	return Movies(queryMods...)
}

// LoadMainActorMovies allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (actorL) LoadMainActorMovies(ctx context.Context, e boil.ContextExecutor, singular bool, maybeActor interface{}, mods queries.Applicator) error {
	var slice []*Actor
	var object *Actor

	if singular {
		var ok bool
		object, ok = maybeActor.(*Actor)
		if !ok {
			object = new(Actor)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeActor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeActor))
			}
		}
	} else {
		s, ok := maybeActor.(*[]*Actor)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeActor)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeActor))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &actorR{}
		}
		args = append(args, object.ActorID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &actorR{}
			}

			for _, a := range args {
				if a == obj.ActorID {
					continue Outer
				}
			}

			args = append(args, obj.ActorID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`movies`),
		qm.WhereIn(`movies.main_actor_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load movies")
	}

	var resultSlice []*Movie
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice movies")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on movies")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for movies")
	}

	if len(movieAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MainActorMovies = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &movieR{}
			}
			foreign.R.MainActor = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ActorID == foreign.MainActorID {
				local.R.MainActorMovies = append(local.R.MainActorMovies, foreign)
				if foreign.R == nil {
					foreign.R = &movieR{}
				}
				foreign.R.MainActor = local
				break
			}
		}
	}

	return nil
}

// AddMainActorMovies adds the given related objects to the existing relationships
// of the actor, optionally inserting them as new records.
// Appends related to o.R.MainActorMovies.
// Sets related.R.MainActor appropriately.
func (o *Actor) AddMainActorMovies(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Movie) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.MainActorID = o.ActorID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"movies\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"main_actor_id"}),
				strmangle.WhereClause("\"", "\"", 2, moviePrimaryKeyColumns),
			)
			values := []interface{}{o.ActorID, rel.MovieID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.MainActorID = o.ActorID
		}
	}

	if o.R == nil {
		o.R = &actorR{
			MainActorMovies: related,
		}
	} else {
		o.R.MainActorMovies = append(o.R.MainActorMovies, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &movieR{
				MainActor: o,
			}
		} else {
			rel.R.MainActor = o
		}
	}
	return nil
}

// Actors retrieves all the records using an executor.
func Actors(mods ...qm.QueryMod) actorQuery {
	mods = append(mods, qm.From("\"actors\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"actors\".*"})
	}

	return actorQuery{q}
}

// FindActor retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindActor(ctx context.Context, exec boil.ContextExecutor, actorID int64, selectCols ...string) (*Actor, error) {
	actorObj := &Actor{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"actors\" where \"actor_id\"=$1", sel,
	)

	q := queries.Raw(query, actorID)

	err := q.Bind(ctx, exec, actorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from actors")
	}

	if err = actorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return actorObj, err
	}

	return actorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Actor) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no actors provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(actorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	actorInsertCacheMut.RLock()
	cache, cached := actorInsertCache[key]
	actorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			actorAllColumns,
			actorColumnsWithDefault,
			actorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(actorType, actorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(actorType, actorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"actors\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"actors\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into actors")
	}

	if !cached {
		actorInsertCacheMut.Lock()
		actorInsertCache[key] = cache
		actorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Actor.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Actor) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	actorUpdateCacheMut.RLock()
	cache, cached := actorUpdateCache[key]
	actorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			actorAllColumns,
			actorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update actors, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"actors\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, actorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(actorType, actorMapping, append(wl, actorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update actors row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for actors")
	}

	if !cached {
		actorUpdateCacheMut.Lock()
		actorUpdateCache[key] = cache
		actorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q actorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for actors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for actors")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ActorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"actors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, actorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in actor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all actor")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Actor) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no actors provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(actorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	actorUpsertCacheMut.RLock()
	cache, cached := actorUpsertCache[key]
	actorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			actorAllColumns,
			actorColumnsWithDefault,
			actorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			actorAllColumns,
			actorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert actors, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(actorPrimaryKeyColumns))
			copy(conflict, actorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"actors\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(actorType, actorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(actorType, actorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert actors")
	}

	if !cached {
		actorUpsertCacheMut.Lock()
		actorUpsertCache[key] = cache
		actorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Actor record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Actor) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Actor provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), actorPrimaryKeyMapping)
	sql := "DELETE FROM \"actors\" WHERE \"actor_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from actors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for actors")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q actorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no actorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from actors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for actors")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ActorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(actorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"actors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, actorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from actor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for actors")
	}

	if len(actorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Actor) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindActor(ctx, exec, o.ActorID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ActorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ActorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"actors\".* FROM \"actors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, actorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ActorSlice")
	}

	*o = slice

	return nil
}

// ActorExists checks if the Actor row exists.
func ActorExists(ctx context.Context, exec boil.ContextExecutor, actorID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"actors\" where \"actor_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, actorID)
	}
	row := exec.QueryRowContext(ctx, sql, actorID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if actors exists")
	}

	return exists, nil
}

// Exists checks if the Actor row exists.
func (o *Actor) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ActorExists(ctx, exec, o.ActorID)
}
